import { subDays, setHours, setMinutes } from 'date-fns';
import type { Restaurant, Sector, Table, Reservation } from '@/types/models';

// Get today's date at midnight
const today = new Date();
today.setHours(0, 0, 0, 0);

// Helper to create an ISO datetime string for today at a specific time
function todayAt(hours: number, minutes: number = 0): string {
  const date = setMinutes(setHours(today, hours), minutes);
  return date.toISOString();
}

// Helper to create an ISO datetime string for a past date
function daysAgoAt(days: number, hours: number, minutes: number = 0): string {
  const date = setMinutes(setHours(subDays(today, days), hours), minutes);
  return date.toISOString();
}

export const seedRestaurant: Restaurant = {
  id: 'R1',
  name: 'Bistro Central',
  timezone: 'America/Argentina/Buenos_Aires',
  serviceHours: [
    { start: '12:00', end: '16:00' },
    { start: '20:00', end: '00:00' },
  ],
};

export const seedSectors: Sector[] = [
  { id: 'S1', name: 'Main Hall', color: '#3B82F6', sortOrder: 0 },
  { id: 'S2', name: 'Terrace', color: '#10B981', sortOrder: 1 },
  { id: 'S3', name: 'Private Room', color: '#8B5CF6', sortOrder: 2 },
  { id: 'S4', name: 'Bar Area', color: '#F59E0B', sortOrder: 3 },
];

export const seedTables: Table[] = [
  // Main Hall - 8 tables
  { id: 'T1', sectorId: 'S1', name: 'Table 1', capacity: { min: 2, max: 2 }, sortOrder: 0 },
  { id: 'T2', sectorId: 'S1', name: 'Table 2', capacity: { min: 2, max: 4 }, sortOrder: 1 },
  { id: 'T3', sectorId: 'S1', name: 'Table 3', capacity: { min: 4, max: 6 }, sortOrder: 2 },
  { id: 'T4', sectorId: 'S1', name: 'Table 4', capacity: { min: 2, max: 4 }, sortOrder: 3 },
  { id: 'T5', sectorId: 'S1', name: 'Table 5', capacity: { min: 2, max: 2 }, sortOrder: 4 },
  { id: 'T6', sectorId: 'S1', name: 'Table 6', capacity: { min: 4, max: 6 }, sortOrder: 5 },
  { id: 'T7', sectorId: 'S1', name: 'Table 7', capacity: { min: 6, max: 8 }, sortOrder: 6 },
  { id: 'T8', sectorId: 'S1', name: 'Table 8', capacity: { min: 2, max: 4 }, sortOrder: 7 },
  // Terrace - 6 tables
  { id: 'T9', sectorId: 'S2', name: 'Terrace 1', capacity: { min: 2, max: 4 }, sortOrder: 0 },
  { id: 'T10', sectorId: 'S2', name: 'Terrace 2', capacity: { min: 4, max: 6 }, sortOrder: 1 },
  { id: 'T11', sectorId: 'S2', name: 'Terrace 3', capacity: { min: 2, max: 4 }, sortOrder: 2 },
  { id: 'T12', sectorId: 'S2', name: 'Terrace 4', capacity: { min: 4, max: 8 }, sortOrder: 3 },
  { id: 'T13', sectorId: 'S2', name: 'Terrace 5', capacity: { min: 2, max: 2 }, sortOrder: 4 },
  { id: 'T14', sectorId: 'S2', name: 'Terrace 6', capacity: { min: 6, max: 10 }, sortOrder: 5 },
  // Private Room - 4 tables
  { id: 'T15', sectorId: 'S3', name: 'Private 1', capacity: { min: 6, max: 10 }, sortOrder: 0 },
  { id: 'T16', sectorId: 'S3', name: 'Private 2', capacity: { min: 8, max: 12 }, sortOrder: 1 },
  { id: 'T17', sectorId: 'S3', name: 'Private 3', capacity: { min: 4, max: 6 }, sortOrder: 2 },
  { id: 'T18', sectorId: 'S3', name: 'Private 4', capacity: { min: 10, max: 16 }, sortOrder: 3 },
  // Bar Area - 6 tables
  { id: 'T19', sectorId: 'S4', name: 'Bar 1', capacity: { min: 2, max: 2 }, sortOrder: 0 },
  { id: 'T20', sectorId: 'S4', name: 'Bar 2', capacity: { min: 2, max: 2 }, sortOrder: 1 },
  { id: 'T21', sectorId: 'S4', name: 'Bar 3', capacity: { min: 2, max: 4 }, sortOrder: 2 },
  { id: 'T22', sectorId: 'S4', name: 'Bar 4', capacity: { min: 2, max: 4 }, sortOrder: 3 },
  { id: 'T23', sectorId: 'S4', name: 'Bar 5', capacity: { min: 4, max: 6 }, sortOrder: 4 },
  { id: 'T24', sectorId: 'S4', name: 'Bar 6', capacity: { min: 2, max: 2 }, sortOrder: 5 },
];

export const seedReservations: Reservation[] = [
  // Main Hall - Lunch Service
  {
    id: 'RES_001',
    tableId: 'T1',
    customer: { name: 'John Doe', phone: '+54 9 11 5555-1234', email: 'john@example.com' },
    partySize: 2,
    startTime: todayAt(12, 0),
    endTime: todayAt(13, 30),
    durationMinutes: 90,
    status: 'FINISHED',
    priority: 'STANDARD',
    source: 'web',
    createdAt: daysAgoAt(1, 15, 30),
    updatedAt: todayAt(13, 30),
  },
  {
    id: 'RES_002',
    tableId: 'T2',
    customer: { name: 'Maria Garcia', phone: '+54 9 11 5555-2345' },
    partySize: 3,
    startTime: todayAt(12, 30),
    endTime: todayAt(14, 0),
    durationMinutes: 90,
    status: 'FINISHED',
    priority: 'STANDARD',
    source: 'phone',
    createdAt: daysAgoAt(1, 10, 0),
    updatedAt: todayAt(14, 0),
  },
  {
    id: 'RES_003',
    tableId: 'T3',
    customer: { name: 'Carlos Ruiz', phone: '+54 9 11 5555-3456', email: 'carlos@company.com' },
    partySize: 5,
    startTime: todayAt(13, 0),
    endTime: todayAt(15, 0),
    durationMinutes: 120,
    status: 'FINISHED',
    priority: 'VIP',
    notes: 'Business lunch - needs quiet table',
    source: 'web',
    createdAt: daysAgoAt(2, 9, 0),
    updatedAt: todayAt(15, 0),
  },
  {
    id: 'RES_004',
    tableId: 'T4',
    customer: { name: 'Laura Martinez', phone: '+54 9 11 5555-4567' },
    partySize: 4,
    startTime: todayAt(12, 0),
    endTime: todayAt(13, 30),
    durationMinutes: 90,
    status: 'FINISHED',
    priority: 'STANDARD',
    source: 'phone',
    createdAt: todayAt(11, 0),
    updatedAt: todayAt(13, 30),
  },
  {
    id: 'RES_005',
    tableId: 'T5',
    customer: { name: 'Pedro Sanchez', phone: '+54 9 11 5555-5678' },
    partySize: 2,
    startTime: todayAt(13, 30),
    endTime: todayAt(15, 0),
    durationMinutes: 90,
    status: 'FINISHED',
    priority: 'STANDARD',
    source: 'web',
    createdAt: daysAgoAt(1, 20, 0),
    updatedAt: todayAt(15, 0),
  },
  {
    id: 'RES_006',
    tableId: 'T6',
    customer: { name: 'Ana Lopez', phone: '+54 9 11 5555-6789' },
    partySize: 6,
    startTime: todayAt(12, 30),
    endTime: todayAt(14, 30),
    durationMinutes: 120,
    status: 'FINISHED',
    priority: 'LARGE_GROUP',
    notes: 'Family gathering',
    source: 'phone',
    createdAt: daysAgoAt(3, 15, 0),
    updatedAt: todayAt(14, 30),
  },
  {
    id: 'RES_007',
    tableId: 'T7',
    customer: { name: 'Roberto Fernandez', phone: '+54 9 11 5555-7890' },
    partySize: 8,
    startTime: todayAt(13, 0),
    endTime: todayAt(15, 30),
    durationMinutes: 150,
    status: 'FINISHED',
    priority: 'LARGE_GROUP',
    notes: 'Birthday party',
    source: 'web',
    createdAt: daysAgoAt(5, 12, 0),
    updatedAt: todayAt(15, 30),
  },

  // Main Hall - Dinner Service
  {
    id: 'RES_008',
    tableId: 'T1',
    customer: { name: 'Sofia Moreno', phone: '+54 9 11 5555-8901' },
    partySize: 2,
    startTime: todayAt(20, 0),
    endTime: todayAt(21, 30),
    durationMinutes: 90,
    status: 'CONFIRMED',
    priority: 'STANDARD',
    source: 'web',
    createdAt: daysAgoAt(1, 18, 0),
    updatedAt: daysAgoAt(1, 18, 0),
  },
  {
    id: 'RES_009',
    tableId: 'T1',
    customer: { name: 'Diego Torres', phone: '+54 9 11 5555-9012' },
    partySize: 2,
    startTime: todayAt(22, 0),
    endTime: todayAt(23, 30),
    durationMinutes: 90,
    status: 'PENDING',
    priority: 'STANDARD',
    source: 'phone',
    createdAt: todayAt(16, 0),
    updatedAt: todayAt(16, 0),
  },
  {
    id: 'RES_010',
    tableId: 'T2',
    customer: { name: 'Isabella Vega', phone: '+54 9 11 5555-0123', email: 'isabella@mail.com' },
    partySize: 4,
    startTime: todayAt(20, 30),
    endTime: todayAt(22, 30),
    durationMinutes: 120,
    status: 'SEATED',
    priority: 'VIP',
    notes: 'Anniversary dinner - champagne ready',
    source: 'web',
    createdAt: daysAgoAt(2, 14, 0),
    updatedAt: todayAt(20, 35),
  },
  {
    id: 'RES_011',
    tableId: 'T3',
    customer: { name: 'Mateo Herrera', phone: '+54 9 11 5555-1235' },
    partySize: 6,
    startTime: todayAt(21, 0),
    endTime: todayAt(23, 0),
    durationMinutes: 120,
    status: 'CONFIRMED',
    priority: 'LARGE_GROUP',
    source: 'phone',
    createdAt: daysAgoAt(1, 11, 0),
    updatedAt: daysAgoAt(1, 11, 0),
  },
  {
    id: 'RES_012',
    tableId: 'T4',
    customer: { name: 'Valentina Cruz', phone: '+54 9 11 5555-2346' },
    partySize: 3,
    startTime: todayAt(20, 0),
    endTime: todayAt(21, 30),
    durationMinutes: 90,
    status: 'SEATED',
    priority: 'STANDARD',
    source: 'web',
    createdAt: todayAt(15, 0),
    updatedAt: todayAt(20, 5),
  },
  {
    id: 'RES_013',
    tableId: 'T5',
    customer: { name: 'Lucas Romero', phone: '+54 9 11 5555-3457' },
    partySize: 2,
    startTime: todayAt(21, 30),
    endTime: todayAt(23, 0),
    durationMinutes: 90,
    status: 'CONFIRMED',
    priority: 'STANDARD',
    source: 'phone',
    createdAt: todayAt(12, 0),
    updatedAt: todayAt(12, 0),
  },
  {
    id: 'RES_014',
    tableId: 'T6',
    customer: { name: 'Camila Ortiz', phone: '+54 9 11 5555-4568' },
    partySize: 5,
    startTime: todayAt(20, 0),
    endTime: todayAt(22, 0),
    durationMinutes: 120,
    status: 'SEATED',
    priority: 'STANDARD',
    source: 'web',
    createdAt: daysAgoAt(1, 9, 0),
    updatedAt: todayAt(20, 10),
  },
  {
    id: 'RES_015',
    tableId: 'T7',
    customer: { name: 'Sebastian Diaz', phone: '+54 9 11 5555-5679', email: 'sdiaz@corp.com' },
    partySize: 7,
    startTime: todayAt(20, 30),
    endTime: todayAt(23, 0),
    durationMinutes: 150,
    status: 'CONFIRMED',
    priority: 'VIP',
    notes: 'Corporate dinner - separate checks',
    source: 'web',
    createdAt: daysAgoAt(3, 10, 0),
    updatedAt: daysAgoAt(3, 10, 0),
  },
  {
    id: 'RES_016',
    tableId: 'T8',
    customer: { name: 'Emma Navarro', phone: '+54 9 11 5555-6780' },
    partySize: 4,
    startTime: todayAt(22, 0),
    endTime: todayAt(23, 30),
    durationMinutes: 90,
    status: 'PENDING',
    priority: 'STANDARD',
    source: 'phone',
    createdAt: todayAt(19, 0),
    updatedAt: todayAt(19, 0),
  },

  // Terrace - Lunch
  {
    id: 'RES_017',
    tableId: 'T9',
    customer: { name: 'Nicolas Soto', phone: '+54 9 11 5555-7891' },
    partySize: 4,
    startTime: todayAt(12, 0),
    endTime: todayAt(14, 0),
    durationMinutes: 120,
    status: 'FINISHED',
    priority: 'STANDARD',
    source: 'web',
    createdAt: daysAgoAt(1, 21, 0),
    updatedAt: todayAt(14, 0),
  },
  {
    id: 'RES_018',
    tableId: 'T10',
    customer: { name: 'Victoria Reyes', phone: '+54 9 11 5555-8902' },
    partySize: 5,
    startTime: todayAt(13, 0),
    endTime: todayAt(15, 0),
    durationMinutes: 120,
    status: 'FINISHED',
    priority: 'STANDARD',
    source: 'phone',
    createdAt: daysAgoAt(2, 17, 0),
    updatedAt: todayAt(15, 0),
  },
  {
    id: 'RES_019',
    tableId: 'T11',
    customer: { name: 'Gabriel Mendoza', phone: '+54 9 11 5555-9013' },
    partySize: 2,
    startTime: todayAt(12, 30),
    endTime: todayAt(14, 0),
    durationMinutes: 90,
    status: 'NO_SHOW',
    priority: 'STANDARD',
    source: 'web',
    createdAt: daysAgoAt(1, 16, 0),
    updatedAt: todayAt(13, 0),
  },
  {
    id: 'RES_020',
    tableId: 'T12',
    customer: { name: 'Martina Castro', phone: '+54 9 11 5555-0124' },
    partySize: 6,
    startTime: todayAt(12, 0),
    endTime: todayAt(14, 30),
    durationMinutes: 150,
    status: 'FINISHED',
    priority: 'LARGE_GROUP',
    notes: 'Outdoor seating preferred',
    source: 'phone',
    createdAt: daysAgoAt(4, 14, 0),
    updatedAt: todayAt(14, 30),
  },

  // Terrace - Dinner
  {
    id: 'RES_021',
    tableId: 'T9',
    customer: { name: 'Benjamin Flores', phone: '+54 9 11 5555-1236' },
    partySize: 3,
    startTime: todayAt(20, 0),
    endTime: todayAt(21, 30),
    durationMinutes: 90,
    status: 'SEATED',
    priority: 'STANDARD',
    source: 'web',
    createdAt: todayAt(14, 0),
    updatedAt: todayAt(20, 5),
  },
  {
    id: 'RES_022',
    tableId: 'T10',
    customer: { name: 'Lucia Ramos', phone: '+54 9 11 5555-2347', email: 'lucia.ramos@email.com' },
    partySize: 6,
    startTime: todayAt(20, 30),
    endTime: todayAt(22, 30),
    durationMinutes: 120,
    status: 'CONFIRMED',
    priority: 'VIP',
    notes: 'Allergies: shellfish, nuts',
    source: 'web',
    createdAt: daysAgoAt(2, 11, 0),
    updatedAt: daysAgoAt(2, 11, 0),
  },
  {
    id: 'RES_023',
    tableId: 'T11',
    customer: { name: 'Tomas Vargas', phone: '+54 9 11 5555-3458' },
    partySize: 4,
    startTime: todayAt(21, 0),
    endTime: todayAt(22, 30),
    durationMinutes: 90,
    status: 'CONFIRMED',
    priority: 'STANDARD',
    source: 'phone',
    createdAt: todayAt(10, 0),
    updatedAt: todayAt(10, 0),
  },
  {
    id: 'RES_024',
    tableId: 'T12',
    customer: { name: 'Paula Guerrero', phone: '+54 9 11 5555-4569' },
    partySize: 8,
    startTime: todayAt(20, 0),
    endTime: todayAt(22, 30),
    durationMinutes: 150,
    status: 'SEATED',
    priority: 'LARGE_GROUP',
    notes: 'Celebration - cake coming at 21:30',
    source: 'web',
    createdAt: daysAgoAt(3, 16, 0),
    updatedAt: todayAt(20, 10),
  },
  {
    id: 'RES_025',
    tableId: 'T13',
    customer: { name: 'Julian Rios', phone: '+54 9 11 5555-5670' },
    partySize: 2,
    startTime: todayAt(22, 0),
    endTime: todayAt(23, 30),
    durationMinutes: 90,
    status: 'PENDING',
    priority: 'STANDARD',
    source: 'phone',
    createdAt: todayAt(18, 0),
    updatedAt: todayAt(18, 0),
  },
  {
    id: 'RES_026',
    tableId: 'T14',
    customer: { name: 'Antonella Silva', phone: '+54 9 11 5555-6781' },
    partySize: 10,
    startTime: todayAt(20, 30),
    endTime: todayAt(23, 30),
    durationMinutes: 180,
    status: 'CONFIRMED',
    priority: 'VIP',
    notes: 'Wedding anniversary - 10 guests confirmed',
    source: 'web',
    createdAt: daysAgoAt(7, 9, 0),
    updatedAt: daysAgoAt(7, 9, 0),
  },

  // Private Room - All day
  {
    id: 'RES_027',
    tableId: 'T15',
    customer: { name: 'Corporate Events Inc', phone: '+54 9 11 5555-7892', email: 'events@corp.com' },
    partySize: 10,
    startTime: todayAt(12, 0),
    endTime: todayAt(15, 0),
    durationMinutes: 180,
    status: 'FINISHED',
    priority: 'VIP',
    notes: 'Board meeting lunch - AV equipment needed',
    source: 'web',
    createdAt: daysAgoAt(14, 10, 0),
    updatedAt: todayAt(15, 0),
  },
  {
    id: 'RES_028',
    tableId: 'T15',
    customer: { name: 'Ricardo Medina', phone: '+54 9 11 5555-8903' },
    partySize: 8,
    startTime: todayAt(20, 0),
    endTime: todayAt(23, 0),
    durationMinutes: 180,
    status: 'CONFIRMED',
    priority: 'LARGE_GROUP',
    notes: 'Birthday party',
    source: 'phone',
    createdAt: daysAgoAt(5, 15, 0),
    updatedAt: daysAgoAt(5, 15, 0),
  },
  {
    id: 'RES_029',
    tableId: 'T16',
    customer: { name: 'Tech Startup LLC', phone: '+54 9 11 5555-9014', email: 'hello@startup.io' },
    partySize: 12,
    startTime: todayAt(12, 30),
    endTime: todayAt(15, 30),
    durationMinutes: 180,
    status: 'FINISHED',
    priority: 'VIP',
    notes: 'Team lunch - vegetarian options needed',
    source: 'web',
    createdAt: daysAgoAt(10, 14, 0),
    updatedAt: todayAt(15, 30),
  },
  {
    id: 'RES_030',
    tableId: 'T16',
    customer: { name: 'Elena Paredes', phone: '+54 9 11 5555-0125' },
    partySize: 10,
    startTime: todayAt(20, 30),
    endTime: todayAt(23, 30),
    durationMinutes: 180,
    status: 'CONFIRMED',
    priority: 'LARGE_GROUP',
    notes: 'Engagement party',
    source: 'web',
    createdAt: daysAgoAt(6, 11, 0),
    updatedAt: daysAgoAt(6, 11, 0),
  },
  {
    id: 'RES_031',
    tableId: 'T17',
    customer: { name: 'Oscar Delgado', phone: '+54 9 11 5555-1237' },
    partySize: 5,
    startTime: todayAt(21, 0),
    endTime: todayAt(23, 0),
    durationMinutes: 120,
    status: 'CONFIRMED',
    priority: 'STANDARD',
    source: 'phone',
    createdAt: daysAgoAt(1, 17, 0),
    updatedAt: daysAgoAt(1, 17, 0),
  },
  {
    id: 'RES_032',
    tableId: 'T18',
    customer: { name: 'Law Firm Associates', phone: '+54 9 11 5555-2348', email: 'events@lawfirm.com' },
    partySize: 14,
    startTime: todayAt(20, 0),
    endTime: todayAt(23, 30),
    durationMinutes: 210,
    status: 'SEATED',
    priority: 'VIP',
    notes: 'Partner dinner - premium wine selection',
    source: 'web',
    createdAt: daysAgoAt(12, 9, 0),
    updatedAt: todayAt(20, 15),
  },

  // Bar Area
  {
    id: 'RES_033',
    tableId: 'T19',
    customer: { name: 'Andrea Molina', phone: '+54 9 11 5555-3459' },
    partySize: 2,
    startTime: todayAt(20, 0),
    endTime: todayAt(21, 0),
    durationMinutes: 60,
    status: 'SEATED',
    priority: 'STANDARD',
    source: 'phone',
    createdAt: todayAt(19, 30),
    updatedAt: todayAt(20, 0),
  },
  {
    id: 'RES_034',
    tableId: 'T20',
    customer: { name: 'Fernando Aguilar', phone: '+54 9 11 5555-4560' },
    partySize: 2,
    startTime: todayAt(21, 0),
    endTime: todayAt(22, 30),
    durationMinutes: 90,
    status: 'CONFIRMED',
    priority: 'STANDARD',
    source: 'web',
    createdAt: todayAt(13, 0),
    updatedAt: todayAt(13, 0),
  },
  {
    id: 'RES_035',
    tableId: 'T21',
    customer: { name: 'Carla Benitez', phone: '+54 9 11 5555-5671' },
    partySize: 3,
    startTime: todayAt(20, 30),
    endTime: todayAt(22, 0),
    durationMinutes: 90,
    status: 'SEATED',
    priority: 'STANDARD',
    source: 'phone',
    createdAt: todayAt(17, 0),
    updatedAt: todayAt(20, 35),
  },
  {
    id: 'RES_036',
    tableId: 'T22',
    customer: { name: 'Hugo Cabrera', phone: '+54 9 11 5555-6782' },
    partySize: 4,
    startTime: todayAt(22, 0),
    endTime: todayAt(23, 30),
    durationMinutes: 90,
    status: 'PENDING',
    priority: 'STANDARD',
    source: 'web',
    createdAt: todayAt(20, 0),
    updatedAt: todayAt(20, 0),
  },
  {
    id: 'RES_037',
    tableId: 'T23',
    customer: { name: 'Daniela Espinoza', phone: '+54 9 11 5555-7893' },
    partySize: 5,
    startTime: todayAt(20, 0),
    endTime: todayAt(22, 0),
    durationMinutes: 120,
    status: 'SEATED',
    priority: 'STANDARD',
    notes: 'Happy hour group',
    source: 'phone',
    createdAt: todayAt(16, 0),
    updatedAt: todayAt(20, 10),
  },
  {
    id: 'RES_038',
    tableId: 'T24',
    customer: { name: 'Ivan Fuentes', phone: '+54 9 11 5555-8904' },
    partySize: 2,
    startTime: todayAt(21, 30),
    endTime: todayAt(23, 0),
    durationMinutes: 90,
    status: 'CONFIRMED',
    priority: 'STANDARD',
    source: 'web',
    createdAt: todayAt(11, 0),
    updatedAt: todayAt(11, 0),
  },

  // Some cancelled reservations
  {
    id: 'RES_039',
    tableId: 'T8',
    customer: { name: 'Cancelled Guest', phone: '+54 9 11 5555-0000' },
    partySize: 2,
    startTime: todayAt(20, 0),
    endTime: todayAt(21, 30),
    durationMinutes: 90,
    status: 'CANCELLED',
    priority: 'STANDARD',
    source: 'web',
    createdAt: daysAgoAt(1, 12, 0),
    updatedAt: todayAt(18, 0),
  },
  {
    id: 'RES_040',
    tableId: 'T13',
    customer: { name: 'No Show Example', phone: '+54 9 11 5555-1111' },
    partySize: 2,
    startTime: todayAt(20, 0),
    endTime: todayAt(21, 30),
    durationMinutes: 90,
    status: 'NO_SHOW',
    priority: 'STANDARD',
    source: 'phone',
    createdAt: daysAgoAt(1, 14, 0),
    updatedAt: todayAt(20, 30),
  },
];
